services:
  - type: web
    name: 360nurse
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nurse360
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false

databases:
  - name: nurse360
    databaseName: nurse360
    user: favour
    plan: free
